CREATE PROCEDURE AllowSeats
@row int,
@hall nvarchar(30),
@session int
AS BEGIN
	DECLARE @COUNTSEATS INT=1;
	CREATE TABLE #FREESEATS
	(
		FREESEAT int
	);
	WHILE(@COUNTSEATS<=(SELECT H.SEATS FROM SESSION S INNER JOIN HALL H ON H.ID=S.HALL_ID
	WHERE S.ID=@session AND H.NAME=@hall))
	BEGIN
	 INSERT #FREESEATS(FREESEAT) values(@COUNTSEATS);
	 SET @COUNTSEATS = @COUNTSEATS + 1;
	END;
	SELECT FREESEAT FROM #FREESEATS EXCEPT
	SELECT T.SEAT FROM SESSION S INNER JOIN HALL H ON H.ID=S.HALL_ID INNER JOIN TICKETS T ON T.SESSION_ID=S.ID
	WHERE T.ROW=@row AND  S.ID=@session AND H.NAME=@hall; 
END;

DROP PROCEDURE AllowSeats;

EXEC AllowSeats @row=8,  @hall='Большой', @session=8;

