USE master;

CREATE LOGIN ADMINISTRATOR_LOG
    WITH PASSWORD = 'P@$$w0rd',
	DEFAULT_DATABASE = [Cinema],
	DEFAULT_LANGUAGE = [русский];

USE Cinema;

CREATE USER ADMINISTRATOR
    FOR LOGIN ADMINISTRATOR_LOG
	WITH DEFAULT_SCHEMA = [dbo];

GRANT EXECUTE TO ADMINISTRATOR;



CREATE LOGIN CLIENT_LOG
    WITH PASSWORD = '1111',
	DEFAULT_DATABASE = [Cinema],
	DEFAULT_LANGUAGE = [русский];

CREATE USER CLIENT
    FOR LOGIN CLIENT_LOG
	WITH DEFAULT_SCHEMA = [dbo];

GRANT EXECUTE ON OBJECT::Authorisation TO CLIENT;
GRANT EXECUTE ON OBJECT::Registration TO CLIENT;

GRANT EXECUTE ON OBJECT::TextSearch TO CLIENT;
GRANT EXECUTE ON OBJECT::GetActorInfo TO CLIENT;
GRANT EXECUTE ON OBJECT::GetCinemaInfo TO CLIENT;
GRANT EXECUTE ON OBJECT::GetMovieInfo TO CLIENT;
GRANT EXECUTE ON OBJECT::GetSessionInfo TO CLIENT;
GRANT EXECUTE ON OBJECT::SelectFreeSeats TO CLIENT;
GRANT EXECUTE ON OBJECT::SelectPrice TO CLIENT;
GRANT EXECUTE ON OBJECT::GetGenres TO CLIENT;
GRANT EXECUTE ON OBJECT::UserInfo TO CLIENT;
GRANT EXECUTE ON OBJECT::GetTicketInfo TO CLIENT;
GRANT EXECUTE ON OBJECT::GetStudiosInfo TO CLIENT;
GRANT EXECUTE ON OBJECT::GetSetActors TO CLIENT;
GRANT EXECUTE ON OBJECT::GetSetGenres TO CLIENT;
GRANT EXECUTE ON OBJECT::AllowRows TO CLIENT;
GRANT EXECUTE ON OBJECT::AllowSeats TO CLIENT;
GRANT EXECUTE ON OBJECT::CheckSeats TO CLIENT;

GRANT EXECUTE ON OBJECT::ImportFromXML TO CLIENT;
GRANT EXECUTE ON OBJECT::ExportToXML TO CLIENT;
GRANT EXECUTE ON OBJECT::ExportIntoXML TO CLIENT;
GRANT EXECUTE ON OBJECT::ExportIntoXML TO CLIENT;

GRANT EXECUTE ON OBJECT::DeleteTicket TO CLIENT;
GRANT EXECUTE ON OBJECT::InsertPurchase TO CLIENT;
GRANT EXECUTE ON OBJECT::InsertTicket TO CLIENT;








--EXEC sp_stored_procedures 




