USE master;

CREATE LOGIN ADMINISTRATOR_LOG
    WITH PASSWORD = 'P@$$w0rd',
	DEFAULT_DATABASE = [Cinema],
	DEFAULT_LANGUAGE = [русский];

USE Cinema;

CREATE USER ADMINISTRATOR
    FOR LOGIN ADMINISTRATOR_LOG
	WITH DEFAULT_SCHEMA = [dbo];

GRANT EXECUTE TO ADMINISTRATOR;
GRANT SELECT TO ADMINISTRATOR;




CREATE LOGIN CLIENT_LOG
    WITH PASSWORD = '1111',
	DEFAULT_DATABASE = [Cinema],
	DEFAULT_LANGUAGE = [русский];

CREATE USER CLIENT
    FOR LOGIN CLIENT_LOG
	WITH DEFAULT_SCHEMA = [dbo];

GRANT EXECUTE ON OBJECT::Authorisation TO CLIENT;
GRANT EXECUTE ON OBJECT::FullTextSearch TO CLIENT;
GRANT EXECUTE ON OBJECT::GetActorInfo TO CLIENT;
GRANT EXECUTE ON OBJECT::GetCinemaInfo TO CLIENT;
GRANT EXECUTE ON OBJECT::GetMovieInfo TO CLIENT;
GRANT EXECUTE ON OBJECT::GetSessionInfo TO CLIENT;
GRANT EXECUTE ON OBJECT::InsertPurchase TO CLIENT;
GRANT EXECUTE ON OBJECT::InsertTicket TO CLIENT;
GRANT EXECUTE ON OBJECT::Registration TO CLIENT;
GRANT EXECUTE ON OBJECT::SelectFreeSeats TO CLIENT;
GRANT EXECUTE ON OBJECT::SelectPrice TO CLIENT;

GRANT SELECT TO CLIENT;







--EXEC sp_stored_procedures 




