CREATE PROCEDURE TextSearch
@search nvarchar(max)
AS BEGIN
    BEGIN
	   SELECT DISTINCT M.ID, M.NAME, M.RELEASE, M.RUNNING_TIME, M.PLOT, M.IMAGE, M.TRAILER, C.NAME,  S.NAME
       FROM MOVIE M INNER JOIN COUNTRY C ON C.ID = M.COUNTRY_ID
	   INNER JOIN GENRE_MOVIE GM ON GM.MOVIE_ID = M.ID
       INNER JOIN GENRE G ON G.ID = GM.GENRE_ID
       INNER JOIN STUDIO S ON S.ID = M.STUDIO_ID  
	   where PLOT like '%' + @search + '%'
      or M.NAME like '%' + @search + '%';
    END
END;

DROP PROCEDURE TextSearch;

EXEC TextSearch @search = 'недалеком будущем что-то произошл';


--SELECT M.NAME, M.RELEASE, C.NAME[COUNTRY], G.NAME[GENRE], M.RUNNING_TIME, D.SURNAME, D.NAME, M.SCREENPLAY, M.COMPOSER, A.SURNAME, A.NAME, M.PLOT, M.IMAGE, M.TRAILER 
--FROM MOVIE M INNER JOIN COUNTRY C ON C.ID = M.COUNTRY_ID
--INNER JOIN GENRE G ON G.ID = M.GENRE_ID
--INNER JOIN DIRECTOR D ON D.ID = M.DIRECTOR_ID
--INNER JOIN ACTOR A ON A.ID = M.ACTOR_ID
--WHERE CONTAINS (PLOT, @plot);

