CREATE PROCEDURE FullTextSearch
@plot nvarchar(max)
AS BEGIN
    BEGIN
	   SELECT M.NAME, M.RELEASE, C.NAME[COUNTRY], G.NAME[GENRE], M.RUNNING_TIME, M.SCREENPLAY, M.COMPOSER, A.SURNAME, A.NAME, M.PLOT
       FROM MOVIE M INNER JOIN COUNTRY C ON C.ID = M.COUNTRY_ID
	   INNER JOIN GENRE_MOVIE GM ON M.ID = GM.MOVIE_ID
	   INNER JOIN ACTOR_MOVIE AM ON M.ID = AM.MOVIE_ID
       INNER JOIN GENRE G ON G.ID = GM.GENRE_ID
	   INNER JOIN ACTOR A ON A.ID = AM.ACTOR_ID   
       WHERE CONTAINS (PLOT, @plot);
    END
END;

DROP PROCEDURE FullTextSearch;

--EXEC FullTextSearch @plot = '"Мы - Веном"';


--SELECT M.NAME, M.RELEASE, C.NAME[COUNTRY], G.NAME[GENRE], M.RUNNING_TIME, D.SURNAME, D.NAME, M.SCREENPLAY, M.COMPOSER, A.SURNAME, A.NAME, M.PLOT, M.IMAGE, M.TRAILER 
--FROM MOVIE M INNER JOIN COUNTRY C ON C.ID = M.COUNTRY_ID
--INNER JOIN GENRE G ON G.ID = M.GENRE_ID
--INNER JOIN DIRECTOR D ON D.ID = M.DIRECTOR_ID
--INNER JOIN ACTOR A ON A.ID = M.ACTOR_ID
--WHERE CONTAINS (PLOT, @plot);

