CREATE PROCEDURE GetSessionInfo
@date date = NULL
AS BEGIN
  
  IF (@date IS NOT NULL)
    SELECT M.NAME, H.NAME, S.DATE, S.TIME, S.FREESEATS, S.COST
	FROM SESSION S INNER JOIN MOVIE M ON M.ID = S.MOVIE_ID
	INNER JOIN HALL H ON H.ID = S.HALL_ID WHERE DATE = @date;
	ELSE IF (@date IS NULL)
	BEGIN
    SELECT M.NAME, H.NAME, S.DATE, S.TIME, S.FREESEATS, S.COST
	FROM SESSION S INNER JOIN MOVIE M ON M.ID = S.MOVIE_ID
	INNER JOIN HALL H ON H.ID = S.HALL_ID;
	END
END;
DROP PROCEDURE GetSessionInfo;
EXEC GetSessionInfo @date = '4.12.2018';