--insert country
CREATE PROCEDURE InsertCountry
    @id varchar(10),
    @name NVARCHAR(70)
    as begin 
        INSERT INTO COUNTRY(ID, NAME)
            VALUES(@id, @name);
    end;


	drop procedure InsertCountry;


INSERT INTO COUNTRY(ID, NAME) VALUES('IS', 'Исландия');
INSERT INTO COUNTRY(ID, NAME) VALUES('IN', 'Индия');
INSERT INTO COUNTRY(ID, NAME) VALUES('BY', 'Беларусь');
exec InsertCountry @id='AU', @name='Австралия';
exec InsertCountry @id='AT', @name='Австрия';
exec InsertCountry @id='AZ', @name='Азербайджан';
exec InsertCountry @id='AX', @name='Аландские о-ва';
exec InsertCountry @id='AL', @name='Албания';
exec InsertCountry @id='DZ', @name='Алжир';
exec InsertCountry @id='AI', @name='Ангилья';
exec InsertCountry @id='AO', @name='Ангола';
exec InsertCountry @id='AD', @name='Андорра';
exec InsertCountry @id='AQ', @name='Антарктида';
exec InsertCountry @id='AG', @name='Антигуа и Барбуда';
exec InsertCountry @id='AR', @name='Аргентина';
exec InsertCountry @id='AM', @name='Армения';
exec InsertCountry @id='AW', @name='Аруба';
exec InsertCountry @id='AF', @name='Афганистан';
exec InsertCountry @id='BS', @name='Багамы';
exec InsertCountry @id='BD', @name='Бангладеш';
exec InsertCountry @id='BB', @name='Барбадос';
exec InsertCountry @id='BH', @name='Бахрейн';
--exec InsertCountry @id='BY', @name='Беларусь';
exec InsertCountry @id='BZ', @name='Белиз';
exec InsertCountry @id='BE', @name='Бельгия';
exec InsertCountry @id='BJ', @name='Бенин';
exec InsertCountry @id='BM', @name='Бермуды';
exec InsertCountry @id='BG', @name='Болгария';
exec InsertCountry @id='BO', @name='Боливия';
exec InsertCountry @id='BQ', @name='Бонэйр, Синт-Эстатиус и Саба';
exec InsertCountry @id='BA', @name='Босния и Герцеговина';
exec InsertCountry @id='BW', @name='Ботсвана';
exec InsertCountry @id='BR', @name='Бразилия';
exec InsertCountry @id='IO', @name='Британская территория в Индийском океане';
exec InsertCountry @id='BN', @name='Бруней-Даруссалам';
exec InsertCountry @id='BF', @name='Буркина-Фасо';
exec InsertCountry @id='BI', @name='Бурунди';
exec InsertCountry @id='BT', @name='Бутан';
exec InsertCountry @id='VU', @name='Вануату';
exec InsertCountry @id='VA', @name='Ватикан';
exec InsertCountry @id='GB', @name='Великобритания';
exec InsertCountry @id='HU', @name='Венгрия';
exec InsertCountry @id='VE', @name='Венесуэла';
exec InsertCountry @id='VG', @name='Виргинские о-ва (Британские)';
exec InsertCountry @id='VI', @name='Виргинские о-ва (США)';
exec InsertCountry @id='UM', @name='Внешние малые о-ва (США)';
exec InsertCountry @id='TL', @name='Восточный Тимор';
exec InsertCountry @id='VN', @name='Вьетнам';
exec InsertCountry @id='GA', @name='Габон';
exec InsertCountry @id='HT', @name='Гаити';
exec InsertCountry @id='GY', @name='Гайана';
exec InsertCountry @id='GM', @name='Гамбия';
exec InsertCountry @id='GH', @name='Гана';
exec InsertCountry @id='GP', @name='Гваделупа';
exec InsertCountry @id='GT', @name='Гватемала';
exec InsertCountry @id='GN', @name='Гвинея';
exec InsertCountry @id='GW', @name='Гвинея-Бисау';
exec InsertCountry @id='DE', @name='Германия';
exec InsertCountry @id='GG', @name='Гернси';
exec InsertCountry @id='GI', @name='Гибралтар';
exec InsertCountry @id='HN', @name='Гондурас';
exec InsertCountry @id='HK', @name='Гонконг (специальный административный район)';
exec InsertCountry @id='GD', @name='Гренада';
exec InsertCountry @id='GL', @name='Гренландия';
exec InsertCountry @id='GR', @name='Греция';
exec InsertCountry @id='GE', @name='Грузия';
exec InsertCountry @id='GU', @name='Гуам';
exec InsertCountry @id='DK', @name='Дания';
exec InsertCountry @id='JE', @name='Джерси';
exec InsertCountry @id='DJ', @name='Джибути';
exec InsertCountry @id='DG', @name='Диего-Гарсия';
exec InsertCountry @id='DM', @name='Доминика';
exec InsertCountry @id='DO', @name='Доминиканская Республика';
exec InsertCountry @id='EG', @name='Египет';
exec InsertCountry @id='ZM', @name='Замбия';
exec InsertCountry @id='EH', @name='Западная Сахара';
exec InsertCountry @id='ZW', @name='Зимбабве';
exec InsertCountry @id='IL', @name='Израиль';
--exec InsertCountry @id='IN', @name='Индия';
exec InsertCountry @id='ID', @name='Индонезия';
exec InsertCountry @id='JO', @name='Иордания';
exec InsertCountry @id='IQ', @name='Ирак';
exec InsertCountry @id='IR', @name='Иран';
exec InsertCountry @id='IE', @name='Ирландия';
--exec InsertCountry @id='IS', @name='Исландия';
exec InsertCountry @id='ES', @name='Испания';
exec InsertCountry @id='IT', @name='Италия';
exec InsertCountry @id='YE', @name='Йемен';
exec InsertCountry @id='CV', @name='Кабо-Верде';
exec InsertCountry @id='KZ', @name='Казахстан';
exec InsertCountry @id='KY', @name='Каймановы о-ва';
exec InsertCountry @id='KH', @name='Камбоджа';
exec InsertCountry @id='CM', @name='Камерун';
exec InsertCountry @id='CA', @name='Канада';
exec InsertCountry @id='IC', @name='Канарские о-ва';
exec InsertCountry @id='QA', @name='Катар';
exec InsertCountry @id='KE', @name='Кения';
exec InsertCountry @id='CY', @name='Кипр';
exec InsertCountry @id='KG', @name='Киргизия';
exec InsertCountry @id='KI', @name='Кирибати';
exec InsertCountry @id='CN', @name='Китай';
exec InsertCountry @id='KP', @name='КНДР';
exec InsertCountry @id='CC', @name='Кокосовые о-ва';
exec InsertCountry @id='CO', @name='Колумбия';
exec InsertCountry @id='KM', @name='Коморы';
exec InsertCountry @id='CG', @name='Конго - Браззавиль';
exec InsertCountry @id='CD', @name='Конго - Киншаса';
exec InsertCountry @id='XK', @name='Косово';
exec InsertCountry @id='CR', @name='Коста-Рика';
exec InsertCountry @id='CI', @name='Кот-д’Ивуар';
exec InsertCountry @id='CU', @name='Куба';
exec InsertCountry @id='KW', @name='Кувейт';
exec InsertCountry @id='CW', @name='Кюрасао';
exec InsertCountry @id='LA', @name='Лаос';
exec InsertCountry @id='LV', @name='Латвия';
exec InsertCountry @id='LS', @name='Лесото';
exec InsertCountry @id='LR', @name='Либерия';
exec InsertCountry @id='LB', @name='Ливан';
exec InsertCountry @id='LY', @name='Ливия';
exec InsertCountry @id='LT', @name='Литва';
exec InsertCountry @id='LI', @name='Лихтенштейн';
exec InsertCountry @id='LU', @name='Люксембург';
exec InsertCountry @id='MU', @name='Маврикий';
exec InsertCountry @id='MR', @name='Мавритания';
exec InsertCountry @id='MG', @name='Мадагаскар';
exec InsertCountry @id='YT', @name='Майотта';
exec InsertCountry @id='MO', @name='Макао (специальный административный район)';
exec InsertCountry @id='MK', @name='Македония';
exec InsertCountry @id='MW', @name='Малави';
exec InsertCountry @id='MY', @name='Малайзия';
exec InsertCountry @id='ML', @name='Мали';
exec InsertCountry @id='MV', @name='Мальдивы';
exec InsertCountry @id='MT', @name='Мальта';
exec InsertCountry @id='MA', @name='Марокко';
exec InsertCountry @id='MQ', @name='Мартиника';
exec InsertCountry @id='MH', @name='Маршалловы Острова';
exec InsertCountry @id='MX', @name='Мексика';
exec InsertCountry @id='MZ', @name='Мозамбик';
exec InsertCountry @id='MD', @name='Молдова';
exec InsertCountry @id='MC', @name='Монако';
exec InsertCountry @id='MN', @name='Монголия';
exec InsertCountry @id='MS', @name='Монтсеррат';
exec InsertCountry @id='MM', @name='Мьянма (Бирма)';
exec InsertCountry @id='NA', @name='Намибия';
exec InsertCountry @id='NR', @name='Науру';
exec InsertCountry @id='NP', @name='Непал';
exec InsertCountry @id='NE', @name='Нигер';
exec InsertCountry @id='NG', @name='Нигерия';
exec InsertCountry @id='NL', @name='Нидерланды';
exec InsertCountry @id='NI', @name='Никарагуа';
exec InsertCountry @id='NU', @name='Ниуэ';
exec InsertCountry @id='NZ', @name='Новая Зеландия';
exec InsertCountry @id='NC', @name='Новая Каледония';
exec InsertCountry @id='NO', @name='Норвегия';
exec InsertCountry @id='AC', @name='о-в Вознесения';
exec InsertCountry @id='IM', @name='о-в Мэн';
exec InsertCountry @id='NF', @name='о-в Норфолк';
exec InsertCountry @id='CX', @name='о-в Рождества';
exec InsertCountry @id='SH', @name='о-в Св. Елены';
exec InsertCountry @id='TC', @name='о-ва Тёркс и Кайкос';
exec InsertCountry @id='AE', @name='ОАЭ';
exec InsertCountry @id='OM', @name='Оман';
exec InsertCountry @id='UN', @name='Организация Объединенных Наций';
exec InsertCountry @id='CK', @name='Острова Кука';
exec InsertCountry @id='PN', @name='острова Питкэрн';
exec InsertCountry @id='PK', @name='Пакистан';
exec InsertCountry @id='PW', @name='Палау';
exec InsertCountry @id='PS', @name='Палестинские территории';
exec InsertCountry @id='PA', @name='Панама';
exec InsertCountry @id='PG', @name='Папуа – Новая Гвинея';
exec InsertCountry @id='PY', @name='Парагвай';
exec InsertCountry @id='PE', @name='Перу';
exec InsertCountry @id='PL', @name='Польша';
exec InsertCountry @id='PT', @name='Португалия';
exec InsertCountry @id='PR', @name='Пуэрто-Рико';
exec InsertCountry @id='KR', @name='Республика Корея';
exec InsertCountry @id='RE', @name='Реюньон';
exec InsertCountry @id='RU', @name='Россия';
exec InsertCountry @id='RW', @name='Руанда';
exec InsertCountry @id='RO', @name='Румыния';
exec InsertCountry @id='SV', @name='Сальвадор';
exec InsertCountry @id='WS', @name='Самоа';
exec InsertCountry @id='SM', @name='Сан-Марино';
exec InsertCountry @id='ST', @name='Сан-Томе и Принсипи';
exec InsertCountry @id='SA', @name='Саудовская Аравия';
exec InsertCountry @id='SZ', @name='Свазиленд';
exec InsertCountry @id='MP', @name='Северные Марианские о-ва';
exec InsertCountry @id='SC', @name='Сейшельские Острова';
exec InsertCountry @id='BL', @name='Сен-Бартелеми';
exec InsertCountry @id='MF', @name='Сен-Мартен';
exec InsertCountry @id='PM', @name='Сен-Пьер и Микелон';
exec InsertCountry @id='SN', @name='Сенегал';
exec InsertCountry @id='VC', @name='Сент-Винсент и Гренадины';
exec InsertCountry @id='KN', @name='Сент-Китс и Невис';
exec InsertCountry @id='LC', @name='Сент-Люсия';
exec InsertCountry @id='RS', @name='Сербия';
exec InsertCountry @id='EA', @name='Сеута и Мелилья';
exec InsertCountry @id='SG', @name='Сингапур';
exec InsertCountry @id='SX', @name='Синт-Мартен';
exec InsertCountry @id='SY', @name='Сирия';
exec InsertCountry @id='SK', @name='Словакия';
exec InsertCountry @id='SI', @name='Словения';
exec InsertCountry @id='US', @name='США';
exec InsertCountry @id='SB', @name='Соломоновы Острова';
exec InsertCountry @id='SO', @name='Сомали';
exec InsertCountry @id='SD', @name='Судан';
exec InsertCountry @id='SR', @name='Суринам';
exec InsertCountry @id='SL', @name='Сьерра-Леоне';
exec InsertCountry @id='TJ', @name='Таджикистан';
exec InsertCountry @id='TH', @name='Таиланд';
exec InsertCountry @id='TW', @name='Тайвань';
exec InsertCountry @id='TZ', @name='Танзания';
exec InsertCountry @id='TG', @name='Того';
exec InsertCountry @id='TK', @name='Токелау';
exec InsertCountry @id='TT', @name='Тринидад и Тобаго';
exec InsertCountry @id='TA', @name='Тристан-да-Кунья';
exec InsertCountry @id='TV', @name='Тувалу';
exec InsertCountry @id='TN', @name='Тунис';
exec InsertCountry @id='TM', @name='Туркменистан';
exec InsertCountry @id='TR', @name='Турция';
exec InsertCountry @id='UG', @name='Уганда';
exec InsertCountry @id='UZ', @name='Узбекистан';
exec InsertCountry @id='UA', @name='Украина';
exec InsertCountry @id='WF', @name='Уоллис и Футуна';
exec InsertCountry @id='UY', @name='Уругвай';
exec InsertCountry @id='FO', @name='Фарерские о-ва';
exec InsertCountry @id='FM', @name='Федеративные Штаты Микронезии';
exec InsertCountry @id='FJ', @name='Фиджи';
exec InsertCountry @id='PH', @name='Филиппины';
exec InsertCountry @id='FI', @name='Финляндия';
exec InsertCountry @id='FK', @name='Фолклендские о-ва';
exec InsertCountry @id='FR', @name='Франция';
exec InsertCountry @id='GF', @name='Французская Гвиана';
exec InsertCountry @id='PF', @name='Французская Полинезия';
exec InsertCountry @id='TF', @name='Французские Южные территории';
exec InsertCountry @id='HR', @name='Хорватия';
exec InsertCountry @id='CF', @name='ЦАР';
exec InsertCountry @id='TD', @name='Чад';
exec InsertCountry @id='ME', @name='Черногория';
exec InsertCountry @id='CZ', @name='Чехия';
exec InsertCountry @id='CL', @name='Чили';
exec InsertCountry @id='CH', @name='Швейцария';
exec InsertCountry @id='SE', @name='Швеция';
exec InsertCountry @id='SJ', @name='Шпицберген и Ян-Майен';
exec InsertCountry @id='LK', @name='Шри-Ланка';
exec InsertCountry @id='EC', @name='Эквадор';
exec InsertCountry @id='GQ', @name='Экваториальная Гвинея';
exec InsertCountry @id='ER', @name='Эритрея';
exec InsertCountry @id='EE', @name='Эстония';
exec InsertCountry @id='ET', @name='Эфиопия';
exec InsertCountry @id='ZA', @name='ЮАР';
exec InsertCountry @id='GS', @name='Южная Георгия и Южные Сандвичевы о-ва';
exec InsertCountry @id='SS', @name='Южный Судан';
exec InsertCountry @id='JM', @name='Ямайка';
exec InsertCountry @id='JP', @name='Япония';

DELETE COUNTRY;
SELECT * FROM COUNTRY;
DROP PROCEDURE InsertCountry;

CREATE INDEX INDEX_COUNTRY ON COUNTRY(NAME);

SELECT * FROM COUNTRY WITH(INDEX(INDEX_COUNTRY));