CREATE PROCEDURE GetMovieInfo
@name nvarchar(20) = null
--@release date = NULL
AS BEGIN
   --IF (@name IS NOT NULL AND @release IS NOT NULL)
	IF (@name IS NOT NULL)
	         SELECT M.NAME, M.RELEASE, C.NAME[COUNTRY], G.NAME[GENRE], M.RUNNING_TIME, D.SURNAME, D.NAME, M.SCREENPLAY, M.COMPOSER, A.SURNAME, A.NAME, M.PLOT
             FROM MOVIE M INNER JOIN COUNTRY C ON C.ID = M.COUNTRY_ID
             INNER JOIN GENRE G ON G.ID = M.GENRE_ID
             INNER JOIN DIRECTOR D ON D.ID = M.DIRECTOR_ID
             INNER JOIN ACTOR A ON A.ID = M.ACTOR_ID
			 where M.NAME = @name; 
	ELSE IF (@name IS NULL)
	BEGIN
	--NAME, RELEASE, COUNTRY, GENRE, RUNNING_TIME, D.SURNAME, D.NAME, SCREENPLAY, COMPOSER, A.SURNAME, A.NAME, PLOT
	   SELECT M.NAME, M.RELEASE, C.NAME[COUNTRY], G.NAME[GENRE], M.RUNNING_TIME, D.SURNAME, D.NAME, M.SCREENPLAY, M.COMPOSER, A.SURNAME, A.NAME, M.PLOT
       FROM MOVIE M INNER JOIN COUNTRY C ON C.ID = M.COUNTRY_ID
       INNER JOIN GENRE G ON G.ID = M.GENRE_ID
       INNER JOIN DIRECTOR D ON D.ID = M.DIRECTOR_ID
       INNER JOIN ACTOR A ON A.ID = M.ACTOR_ID;
	END
END;


EXEC GetMovieInfo;
SELECT * FROM MOVIE;
DROP PROCEDURE  GetMovieInfo;

SELECT M.NAME, M.RELEASE, C.NAME[COUNTRY], G.NAME[GENRE], M.RUNNING_TIME, D.SURNAME, D.NAME, M.SCREENPLAY, M.COMPOSER, A.SURNAME, A.NAME, M.PLOT, M.IMAGE, M.TRAILER 
FROM MOVIE M INNER JOIN COUNTRY C ON C.ID = M.COUNTRY_ID
INNER JOIN GENRE G ON G.ID = M.GENRE_ID
INNER JOIN DIRECTOR D ON D.ID = M.DIRECTOR_ID
INNER JOIN ACTOR A ON A.ID = M.ACTOR_ID;