CREATE PROCEDURE GetMovieInfo
@name nvarchar(20) = null,
@cinema nvarchar(30) = null,
@studio nvarchar(20) = null,
@country nvarchar(70) = null,
@genre1 nvarchar(30) = null,
@genre2 nvarchar(30) = null,
@genre3 nvarchar(30) = null
--@release date = NULL
AS BEGIN
	IF (@name IS NOT NULL)
	begin
		
	         SELECT DISTINCT M.ID, M.NAME, M.RELEASE, M.RUNNING_TIME, M.PLOT, M.IMAGE, M.TRAILER, C.NAME, S.NAME
		FROM MOVIE M INNER JOIN COUNTRY C ON C.ID = M.COUNTRY_ID
		INNER JOIN GENRE_MOVIE GM ON GM.MOVIE_ID = M.ID
		INNER JOIN GENRE G ON G.ID = GM.GENRE_ID
		INNER JOIN STUDIO S ON S.ID = M.STUDIO_ID
		INNER JOIN ACTOR_MOVIE AM ON AM.MOVIE_ID = M.ID
		INNER JOIN ACTOR A ON A.ID = AM.ACTOR_ID
			 where M.NAME = @name; 
	end;
	ELSE IF (@name IS NULL)
	BEGIN
	   SELECT DISTINCT M.ID, M.NAME, M.RELEASE, M.RUNNING_TIME, M.PLOT, M.IMAGE, M.TRAILER, C.NAME,  M.TRAILER, C.NAME, S.NAME
       FROM MOVIE M INNER JOIN COUNTRY C ON C.ID = M.COUNTRY_ID
	   INNER JOIN GENRE_MOVIE GM ON GM.MOVIE_ID = M.ID
       INNER JOIN GENRE G ON G.ID = GM.GENRE_ID
       INNER JOIN STUDIO S ON S.ID = M.STUDIO_ID
	   INNER JOIN ACTOR_MOVIE AM ON AM.MOVIE_ID = M.ID
       INNER JOIN ACTOR A ON A.ID = AM.ACTOR_ID;
	   
	END
	ELSE IF (@cinema IS NOT NULL)
	BEGIN
	   SELECT M.ID, M.NAME, M.RELEASE, M.RUNNING_TIME, M.PLOT, M.IMAGE, M.TRAILER, C.NAME,  M.TRAILER, C.NAME, S.NAME
       FROM MOVIE M INNER JOIN COUNTRY C ON C.ID = M.COUNTRY_ID
	   INNER JOIN GENRE_MOVIE GM ON GM.MOVIE_ID = M.ID
       INNER JOIN GENRE G ON G.ID = GM.GENRE_ID
       INNER JOIN STUDIO S ON S.ID = M.STUDIO_ID
	   INNER JOIN ACTOR_MOVIE AM ON AM.MOVIE_ID = M.ID
       INNER JOIN ACTOR A ON A.ID = AM.ACTOR_ID
	   INNER JOIN SESSION SE ON M.ID = SE.MOVIE_ID
		INNER JOIN HALL H ON H.ID = SE.HALL_ID INNER JOIN CINEMA CI ON CI.ID = H.CINEMA_ID
	   where CI.NAME=@cinema;
	END
	ELSE IF (@studio IS NOT NULL)
	BEGIN
	   SELECT M.ID, M.NAME, M.RELEASE, M.RUNNING_TIME, M.PLOT, M.IMAGE, M.TRAILER, C.NAME,  M.TRAILER, C.NAME, S.NAME
       FROM MOVIE M INNER JOIN COUNTRY C ON C.ID = M.COUNTRY_ID
	   INNER JOIN GENRE_MOVIE GM ON GM.MOVIE_ID = M.ID
       INNER JOIN GENRE G ON G.ID = GM.GENRE_ID
       INNER JOIN STUDIO S ON S.ID = M.STUDIO_ID
	   INNER JOIN ACTOR_MOVIE AM ON AM.MOVIE_ID = M.ID
       INNER JOIN ACTOR A ON A.ID = AM.ACTOR_ID
	   where S.NAME=@studio;
	END
	ELSE IF (@country IS NOT NULL)
	BEGIN
	   SELECT M.ID, M.NAME, M.RELEASE, M.RUNNING_TIME, M.PLOT, M.IMAGE, M.TRAILER, C.NAME, M.TRAILER, C.NAME, S.NAME
       FROM MOVIE M INNER JOIN COUNTRY C ON C.ID = M.COUNTRY_ID
	   INNER JOIN GENRE_MOVIE GM ON GM.MOVIE_ID = M.ID
       INNER JOIN GENRE G ON G.ID = GM.GENRE_ID
       INNER JOIN STUDIO S ON S.ID = M.STUDIO_ID
	   INNER JOIN ACTOR_MOVIE AM ON AM.MOVIE_ID = M.ID
       INNER JOIN ACTOR A ON A.ID = AM.ACTOR_ID
	   where C.NAME=@country;
	END
	ELSE IF (@genre1 IS NOT NULL or @genre2 IS NOT NULL or @genre3 IS NOT NULL)
	BEGIN
	   SELECT M.ID, M.NAME, M.RELEASE, M.RUNNING_TIME, M.PLOT, M.IMAGE, M.TRAILER, C.NAME, G.NAME, S.NAME
       FROM MOVIE M INNER JOIN COUNTRY C ON C.ID = M.COUNTRY_ID
	   INNER JOIN GENRE_MOVIE GM ON GM.MOVIE_ID = M.ID
       INNER JOIN GENRE G ON G.ID = GM.GENRE_ID
       INNER JOIN STUDIO S ON S.ID = M.STUDIO_ID
	   INNER JOIN ACTOR_MOVIE AM ON AM.MOVIE_ID = M.ID
       INNER JOIN ACTOR A ON A.ID = AM.ACTOR_ID
	   where G.NAME=@genre1
	   INTERSECT
	   SELECT M.ID, M.NAME, M.RELEASE, M.RUNNING_TIME, M.PLOT, M.IMAGE, M.TRAILER, C.NAME, G.NAME, S.NAME 
       FROM MOVIE M INNER JOIN COUNTRY C ON C.ID = M.COUNTRY_ID
	   INNER JOIN GENRE_MOVIE GM ON GM.MOVIE_ID = M.ID
       INNER JOIN GENRE G ON G.ID = GM.GENRE_ID
       INNER JOIN STUDIO S ON S.ID = M.STUDIO_ID
	   INNER JOIN ACTOR_MOVIE AM ON AM.MOVIE_ID = M.ID
       INNER JOIN ACTOR A ON A.ID = AM.ACTOR_ID
	   where G.NAME=@genre2
	   INTERSECT
	   SELECT M.ID, M.NAME, M.RELEASE, M.RUNNING_TIME, M.PLOT, M.IMAGE, M.TRAILER, C.NAME, G.NAME, S.NAME
       FROM MOVIE M INNER JOIN COUNTRY C ON C.ID = M.COUNTRY_ID
	   INNER JOIN GENRE_MOVIE GM ON GM.MOVIE_ID = M.ID
       INNER JOIN GENRE G ON G.ID = GM.GENRE_ID
       INNER JOIN STUDIO S ON S.ID = M.STUDIO_ID
	   INNER JOIN ACTOR_MOVIE AM ON AM.MOVIE_ID = M.ID
       INNER JOIN ACTOR A ON A.ID = AM.ACTOR_ID
	   where G.NAME=@genre3
	END
END;


EXEC GetMovieInfo;
SELECT * FROM MOVIE;
DROP PROCEDURE  GetMovieInfo;

