CREATE PROCEDURE GetSessionInfo
@date date = NULL,
@name nvarchar(max) = NULL
AS BEGIN
  
  IF (@date IS NOT NULL)
    SELECT S.ID[S_ID], M.NAME[Name], H.NAME[Hall], S.DATE[Date], S.TIME[Time], S.FREESEATS[Seats], S.COST[Cost], C.NAME[Cinema]
	FROM SESSION S INNER JOIN MOVIE M ON M.ID = S.MOVIE_ID 
	INNER JOIN HALL H ON H.ID = S.HALL_ID INNER JOIN CINEMA C ON C.ID = H.CINEMA_ID WHERE DATE = @date;
	ELSE IF (@name IS not NULL)
	BEGIN
    SELECT S.ID[S_ID], M.NAME[Name], H.NAME[Hall], S.DATE[Date], S.TIME[Time], S.FREESEATS[Seats], S.COST[Cost], C.NAME[Cinema]
	FROM SESSION S INNER JOIN MOVIE M ON M.ID = S.MOVIE_ID
	INNER JOIN HALL H ON H.ID = S.HALL_ID INNER JOIN CINEMA C ON C.ID = H.CINEMA_ID WHERE M.NAME = @name;
	END
	ELSE IF (@date IS NULL and @name IS NULL)
	BEGIN
    SELECT  S.ID[S_ID], M.NAME[Name], H.NAME[Hall], S.DATE[Date], S.TIME[Time], S.FREESEATS[Seats], S.COST[Cost], C.NAME[Cinema]
	FROM SESSION S INNER JOIN MOVIE M ON M.ID = S.MOVIE_ID
	INNER JOIN HALL H INNER JOIN CINEMA C ON C.ID = H.CINEMA_ID ON H.ID = S.HALL_ID;
	END
	
END;

DROP PROCEDURE GetSessionInfo;

--EXEC GetSessionInfo @date = '4.12.2018';